# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beamable_python_sdk import schemas  # noqa: F401


class AccessLogServiceDetails(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "aggregates",
            "details",
        }
        
        class properties:
        
            @staticmethod
            def aggregates() -> typing.Type['AccessLogAggregates']:
                return AccessLogAggregates
            
            
            class details(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AccessLogResultView']:
                        return AccessLogResultView
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AccessLogResultView'], typing.List['AccessLogResultView']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'details':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AccessLogResultView':
                    return super().__getitem__(i)
            __annotations__ = {
                "aggregates": aggregates,
                "details": details,
            }
    
    aggregates: 'AccessLogAggregates'
    details: MetaOapg.properties.details
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["aggregates"]) -> 'AccessLogAggregates': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["details"]) -> MetaOapg.properties.details: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["aggregates", "details", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["aggregates"]) -> 'AccessLogAggregates': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["details"]) -> MetaOapg.properties.details: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["aggregates", "details", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        aggregates: 'AccessLogAggregates',
        details: typing.Union[MetaOapg.properties.details, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AccessLogServiceDetails':
        return super().__new__(
            cls,
            *args,
            aggregates=aggregates,
            details=details,
            _configuration=_configuration,
            **kwargs,
        )

from beamable_python_sdk.model.access_log_aggregates import AccessLogAggregates
from beamable_python_sdk.model.access_log_result_view import AccessLogResultView
