# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beamable_python_sdk import schemas  # noqa: F401


class AccountPersonallyIdentifiableInformationResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "paymentAudits",
            "stats",
            "account",
        }
        
        class properties:
        
            @staticmethod
            def account() -> typing.Type['Account']:
                return Account
            
            
            class stats(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['StatsResponse']:
                        return StatsResponse
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['StatsResponse'], typing.List['StatsResponse']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'stats':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'StatsResponse':
                    return super().__getitem__(i)
        
            @staticmethod
            def paymentAudits() -> typing.Type['ListAuditResponse']:
                return ListAuditResponse
            __annotations__ = {
                "account": account,
                "stats": stats,
                "paymentAudits": paymentAudits,
            }
    
    paymentAudits: 'ListAuditResponse'
    stats: MetaOapg.properties.stats
    account: 'Account'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["account"]) -> 'Account': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stats"]) -> MetaOapg.properties.stats: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentAudits"]) -> 'ListAuditResponse': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["account", "stats", "paymentAudits", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["account"]) -> 'Account': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stats"]) -> MetaOapg.properties.stats: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentAudits"]) -> 'ListAuditResponse': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["account", "stats", "paymentAudits", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        paymentAudits: 'ListAuditResponse',
        stats: typing.Union[MetaOapg.properties.stats, list, tuple, ],
        account: 'Account',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AccountPersonallyIdentifiableInformationResponse':
        return super().__new__(
            cls,
            *args,
            paymentAudits=paymentAudits,
            stats=stats,
            account=account,
            _configuration=_configuration,
            **kwargs,
        )

from beamable_python_sdk.model.account import Account
from beamable_python_sdk.model.list_audit_response import ListAuditResponse
from beamable_python_sdk.model.stats_response import StatsResponse
