# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beamable_python_sdk import schemas  # noqa: F401


class EntitlementGrantMultiRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def gamerTags() -> typing.Type['EntitlementGrantMultiRequestGamerTags']:
                return EntitlementGrantMultiRequestGamerTags
            
            
            class generators(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['EntitlementGenerator']:
                        return EntitlementGenerator
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['EntitlementGenerator'], typing.List['EntitlementGenerator']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'generators':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'EntitlementGenerator':
                    return super().__getitem__(i)
            __annotations__ = {
                "gamerTags": gamerTags,
                "generators": generators,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gamerTags"]) -> 'EntitlementGrantMultiRequestGamerTags': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["generators"]) -> MetaOapg.properties.generators: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["gamerTags", "generators", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gamerTags"]) -> typing.Union['EntitlementGrantMultiRequestGamerTags', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["generators"]) -> typing.Union[MetaOapg.properties.generators, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["gamerTags", "generators", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        gamerTags: typing.Union['EntitlementGrantMultiRequestGamerTags', schemas.Unset] = schemas.unset,
        generators: typing.Union[MetaOapg.properties.generators, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EntitlementGrantMultiRequest':
        return super().__new__(
            cls,
            *args,
            gamerTags=gamerTags,
            generators=generators,
            _configuration=_configuration,
            **kwargs,
        )

from beamable_python_sdk.model.entitlement_generator import EntitlementGenerator
from beamable_python_sdk.model.entitlement_grant_multi_request_gamer_tags import EntitlementGrantMultiRequestGamerTags
