# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beamable_python_sdk import schemas  # noqa: F401


class LeaderboardAddRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "score",
            "id",
        }
        
        class properties:
            score = schemas.NumberSchema
            id = schemas.IntSchema
            maxScore = schemas.NumberSchema
        
            @staticmethod
            def stats() -> typing.Type['LeaderboardAddRequestStats']:
                return LeaderboardAddRequestStats
            minScore = schemas.NumberSchema
            increment = schemas.BoolSchema
            __annotations__ = {
                "score": score,
                "id": id,
                "maxScore": maxScore,
                "stats": stats,
                "minScore": minScore,
                "increment": increment,
            }
    
    score: MetaOapg.properties.score
    id: MetaOapg.properties.id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["score"]) -> MetaOapg.properties.score: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["maxScore"]) -> MetaOapg.properties.maxScore: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stats"]) -> 'LeaderboardAddRequestStats': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["minScore"]) -> MetaOapg.properties.minScore: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["increment"]) -> MetaOapg.properties.increment: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["score", "id", "maxScore", "stats", "minScore", "increment", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["score"]) -> MetaOapg.properties.score: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["maxScore"]) -> typing.Union[MetaOapg.properties.maxScore, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stats"]) -> typing.Union['LeaderboardAddRequestStats', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["minScore"]) -> typing.Union[MetaOapg.properties.minScore, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["increment"]) -> typing.Union[MetaOapg.properties.increment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["score", "id", "maxScore", "stats", "minScore", "increment", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        score: typing.Union[MetaOapg.properties.score, decimal.Decimal, int, float, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, ],
        maxScore: typing.Union[MetaOapg.properties.maxScore, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        stats: typing.Union['LeaderboardAddRequestStats', schemas.Unset] = schemas.unset,
        minScore: typing.Union[MetaOapg.properties.minScore, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        increment: typing.Union[MetaOapg.properties.increment, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LeaderboardAddRequest':
        return super().__new__(
            cls,
            *args,
            score=score,
            id=id,
            maxScore=maxScore,
            stats=stats,
            minScore=minScore,
            increment=increment,
            _configuration=_configuration,
            **kwargs,
        )

from beamable_python_sdk.model.leaderboard_add_request_stats import LeaderboardAddRequestStats
