# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beamable_python_sdk import schemas  # noqa: F401


class Message(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "receiverGamerTag",
            "senderGamerTag",
            "id",
        }
        
        class properties:
            receiverGamerTag = schemas.IntSchema
            id = schemas.IntSchema
            senderGamerTag = schemas.IntSchema
            roomId = schemas.StrSchema
            gamerTag = schemas.IntSchema
        
            @staticmethod
            def reactions() -> typing.Type['MessageReactions']:
                return MessageReactions
            timestampMillis = schemas.IntSchema
            censoredContent = schemas.StrSchema
            messageId = schemas.StrSchema
            content = schemas.StrSchema
            body = schemas.StrSchema
            expires = schemas.IntSchema
            subject = schemas.StrSchema
            state = schemas.StrSchema
            sent = schemas.IntSchema
            category = schemas.StrSchema
            bodyRef = schemas.IntSchema
            
            
            class attachments(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Attachment']:
                        return Attachment
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Attachment'], typing.List['Attachment']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attachments':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Attachment':
                    return super().__getitem__(i)
        
            @staticmethod
            def rewards() -> typing.Type['MailRewards']:
                return MailRewards
            claimedTimeMs = schemas.IntSchema
            __annotations__ = {
                "receiverGamerTag": receiverGamerTag,
                "id": id,
                "senderGamerTag": senderGamerTag,
                "roomId": roomId,
                "gamerTag": gamerTag,
                "reactions": reactions,
                "timestampMillis": timestampMillis,
                "censoredContent": censoredContent,
                "messageId": messageId,
                "content": content,
                "body": body,
                "expires": expires,
                "subject": subject,
                "state": state,
                "sent": sent,
                "category": category,
                "bodyRef": bodyRef,
                "attachments": attachments,
                "rewards": rewards,
                "claimedTimeMs": claimedTimeMs,
            }
    
    receiverGamerTag: MetaOapg.properties.receiverGamerTag
    senderGamerTag: MetaOapg.properties.senderGamerTag
    id: MetaOapg.properties.id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["receiverGamerTag"]) -> MetaOapg.properties.receiverGamerTag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["senderGamerTag"]) -> MetaOapg.properties.senderGamerTag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["roomId"]) -> MetaOapg.properties.roomId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gamerTag"]) -> MetaOapg.properties.gamerTag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reactions"]) -> 'MessageReactions': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestampMillis"]) -> MetaOapg.properties.timestampMillis: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["censoredContent"]) -> MetaOapg.properties.censoredContent: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["messageId"]) -> MetaOapg.properties.messageId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["content"]) -> MetaOapg.properties.content: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["body"]) -> MetaOapg.properties.body: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expires"]) -> MetaOapg.properties.expires: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subject"]) -> MetaOapg.properties.subject: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["state"]) -> MetaOapg.properties.state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sent"]) -> MetaOapg.properties.sent: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["category"]) -> MetaOapg.properties.category: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bodyRef"]) -> MetaOapg.properties.bodyRef: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attachments"]) -> MetaOapg.properties.attachments: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rewards"]) -> 'MailRewards': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["claimedTimeMs"]) -> MetaOapg.properties.claimedTimeMs: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["receiverGamerTag", "id", "senderGamerTag", "roomId", "gamerTag", "reactions", "timestampMillis", "censoredContent", "messageId", "content", "body", "expires", "subject", "state", "sent", "category", "bodyRef", "attachments", "rewards", "claimedTimeMs", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["receiverGamerTag"]) -> MetaOapg.properties.receiverGamerTag: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["senderGamerTag"]) -> MetaOapg.properties.senderGamerTag: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["roomId"]) -> typing.Union[MetaOapg.properties.roomId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gamerTag"]) -> typing.Union[MetaOapg.properties.gamerTag, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reactions"]) -> typing.Union['MessageReactions', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestampMillis"]) -> typing.Union[MetaOapg.properties.timestampMillis, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["censoredContent"]) -> typing.Union[MetaOapg.properties.censoredContent, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["messageId"]) -> typing.Union[MetaOapg.properties.messageId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["content"]) -> typing.Union[MetaOapg.properties.content, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["body"]) -> typing.Union[MetaOapg.properties.body, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expires"]) -> typing.Union[MetaOapg.properties.expires, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subject"]) -> typing.Union[MetaOapg.properties.subject, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["state"]) -> typing.Union[MetaOapg.properties.state, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sent"]) -> typing.Union[MetaOapg.properties.sent, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["category"]) -> typing.Union[MetaOapg.properties.category, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bodyRef"]) -> typing.Union[MetaOapg.properties.bodyRef, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attachments"]) -> typing.Union[MetaOapg.properties.attachments, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rewards"]) -> typing.Union['MailRewards', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["claimedTimeMs"]) -> typing.Union[MetaOapg.properties.claimedTimeMs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["receiverGamerTag", "id", "senderGamerTag", "roomId", "gamerTag", "reactions", "timestampMillis", "censoredContent", "messageId", "content", "body", "expires", "subject", "state", "sent", "category", "bodyRef", "attachments", "rewards", "claimedTimeMs", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        receiverGamerTag: typing.Union[MetaOapg.properties.receiverGamerTag, decimal.Decimal, int, ],
        senderGamerTag: typing.Union[MetaOapg.properties.senderGamerTag, decimal.Decimal, int, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, ],
        roomId: typing.Union[MetaOapg.properties.roomId, str, schemas.Unset] = schemas.unset,
        gamerTag: typing.Union[MetaOapg.properties.gamerTag, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        reactions: typing.Union['MessageReactions', schemas.Unset] = schemas.unset,
        timestampMillis: typing.Union[MetaOapg.properties.timestampMillis, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        censoredContent: typing.Union[MetaOapg.properties.censoredContent, str, schemas.Unset] = schemas.unset,
        messageId: typing.Union[MetaOapg.properties.messageId, str, schemas.Unset] = schemas.unset,
        content: typing.Union[MetaOapg.properties.content, str, schemas.Unset] = schemas.unset,
        body: typing.Union[MetaOapg.properties.body, str, schemas.Unset] = schemas.unset,
        expires: typing.Union[MetaOapg.properties.expires, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        subject: typing.Union[MetaOapg.properties.subject, str, schemas.Unset] = schemas.unset,
        state: typing.Union[MetaOapg.properties.state, str, schemas.Unset] = schemas.unset,
        sent: typing.Union[MetaOapg.properties.sent, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        category: typing.Union[MetaOapg.properties.category, str, schemas.Unset] = schemas.unset,
        bodyRef: typing.Union[MetaOapg.properties.bodyRef, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        attachments: typing.Union[MetaOapg.properties.attachments, list, tuple, schemas.Unset] = schemas.unset,
        rewards: typing.Union['MailRewards', schemas.Unset] = schemas.unset,
        claimedTimeMs: typing.Union[MetaOapg.properties.claimedTimeMs, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Message':
        return super().__new__(
            cls,
            *args,
            receiverGamerTag=receiverGamerTag,
            senderGamerTag=senderGamerTag,
            id=id,
            roomId=roomId,
            gamerTag=gamerTag,
            reactions=reactions,
            timestampMillis=timestampMillis,
            censoredContent=censoredContent,
            messageId=messageId,
            content=content,
            body=body,
            expires=expires,
            subject=subject,
            state=state,
            sent=sent,
            category=category,
            bodyRef=bodyRef,
            attachments=attachments,
            rewards=rewards,
            claimedTimeMs=claimedTimeMs,
            _configuration=_configuration,
            **kwargs,
        )

from beamable_python_sdk.model.attachment import Attachment
from beamable_python_sdk.model.mail_rewards import MailRewards
from beamable_python_sdk.model.message_reactions import MessageReactions
