# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beamable_python_sdk import schemas  # noqa: F401


class Store(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "storeWithAnnotations$default$3",
        }
        
        class properties:
            store_with_annotationsdefault3 = schemas.BoolSchema
            title = schemas.StrSchema
            activeListingLimit = schemas.IntSchema
            choose = schemas.IntSchema
            
            
            class listings(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Listing']:
                        return Listing
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Listing'], typing.List['Listing']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'listings':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Listing':
                    return super().__getitem__(i)
            showInactiveListings = schemas.BoolSchema
            symbol = schemas.StrSchema
            refreshTime = schemas.IntSchema
        
            @staticmethod
            def store_with_annotationsdefault2() -> typing.Type['DateTime']:
                return DateTime
            __annotations__ = {
                "storeWithAnnotations$default$3": store_with_annotationsdefault3,
                "title": title,
                "activeListingLimit": activeListingLimit,
                "choose": choose,
                "listings": listings,
                "showInactiveListings": showInactiveListings,
                "symbol": symbol,
                "refreshTime": refreshTime,
                "storeWithAnnotations$default$2": store_with_annotationsdefault2,
            }
    
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["storeWithAnnotations$default$3"]) -> MetaOapg.properties.store_with_annotationsdefault3: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activeListingLimit"]) -> MetaOapg.properties.activeListingLimit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["choose"]) -> MetaOapg.properties.choose: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["listings"]) -> MetaOapg.properties.listings: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["showInactiveListings"]) -> MetaOapg.properties.showInactiveListings: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["symbol"]) -> MetaOapg.properties.symbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["refreshTime"]) -> MetaOapg.properties.refreshTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["storeWithAnnotations$default$2"]) -> 'DateTime': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["storeWithAnnotations$default$3", "title", "activeListingLimit", "choose", "listings", "showInactiveListings", "symbol", "refreshTime", "storeWithAnnotations$default$2", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["storeWithAnnotations$default$3"]) -> MetaOapg.properties.store_with_annotationsdefault3: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activeListingLimit"]) -> typing.Union[MetaOapg.properties.activeListingLimit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["choose"]) -> typing.Union[MetaOapg.properties.choose, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["listings"]) -> typing.Union[MetaOapg.properties.listings, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["showInactiveListings"]) -> typing.Union[MetaOapg.properties.showInactiveListings, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["symbol"]) -> typing.Union[MetaOapg.properties.symbol, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["refreshTime"]) -> typing.Union[MetaOapg.properties.refreshTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["storeWithAnnotations$default$2"]) -> typing.Union['DateTime', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["storeWithAnnotations$default$3", "title", "activeListingLimit", "choose", "listings", "showInactiveListings", "symbol", "refreshTime", "storeWithAnnotations$default$2", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        activeListingLimit: typing.Union[MetaOapg.properties.activeListingLimit, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        choose: typing.Union[MetaOapg.properties.choose, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        listings: typing.Union[MetaOapg.properties.listings, list, tuple, schemas.Unset] = schemas.unset,
        showInactiveListings: typing.Union[MetaOapg.properties.showInactiveListings, bool, schemas.Unset] = schemas.unset,
        symbol: typing.Union[MetaOapg.properties.symbol, str, schemas.Unset] = schemas.unset,
        refreshTime: typing.Union[MetaOapg.properties.refreshTime, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Store':
        return super().__new__(
            cls,
            *args,
            title=title,
            activeListingLimit=activeListingLimit,
            choose=choose,
            listings=listings,
            showInactiveListings=showInactiveListings,
            symbol=symbol,
            refreshTime=refreshTime,
            _configuration=_configuration,
            **kwargs,
        )

from beamable_python_sdk.model.date_time import DateTime
from beamable_python_sdk.model.listing import Listing
