# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beamable_python_sdk import schemas  # noqa: F401


class SubscriptionVerificationRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            hubMode = schemas.StrSchema
            hubChallenge = schemas.StrSchema
            hubVerifyToken = schemas.StrSchema
            __annotations__ = {
                "hubMode": hubMode,
                "hubChallenge": hubChallenge,
                "hubVerifyToken": hubVerifyToken,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hubMode"]) -> MetaOapg.properties.hubMode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hubChallenge"]) -> MetaOapg.properties.hubChallenge: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hubVerifyToken"]) -> MetaOapg.properties.hubVerifyToken: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["hubMode", "hubChallenge", "hubVerifyToken", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hubMode"]) -> typing.Union[MetaOapg.properties.hubMode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hubChallenge"]) -> typing.Union[MetaOapg.properties.hubChallenge, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hubVerifyToken"]) -> typing.Union[MetaOapg.properties.hubVerifyToken, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["hubMode", "hubChallenge", "hubVerifyToken", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        hubMode: typing.Union[MetaOapg.properties.hubMode, str, schemas.Unset] = schemas.unset,
        hubChallenge: typing.Union[MetaOapg.properties.hubChallenge, str, schemas.Unset] = schemas.unset,
        hubVerifyToken: typing.Union[MetaOapg.properties.hubVerifyToken, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SubscriptionVerificationRequest':
        return super().__new__(
            cls,
            *args,
            hubMode=hubMode,
            hubChallenge=hubChallenge,
            hubVerifyToken=hubVerifyToken,
            _configuration=_configuration,
            **kwargs,
        )
