# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beamable_python_sdk import schemas  # noqa: F401


class TournamentEntry(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "score",
            "stageChange",
            "rank",
            "playerId",
        }
        
        class properties:
            rank = schemas.IntSchema
            score = schemas.NumberSchema
            playerId = schemas.IntSchema
            stageChange = schemas.IntSchema
            
            
            class currencyRewards(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TournamentReward']:
                        return TournamentReward
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['TournamentReward'], typing.List['TournamentReward']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'currencyRewards':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TournamentReward':
                    return super().__getitem__(i)
            __annotations__ = {
                "rank": rank,
                "score": score,
                "playerId": playerId,
                "stageChange": stageChange,
                "currencyRewards": currencyRewards,
            }
    
    score: MetaOapg.properties.score
    stageChange: MetaOapg.properties.stageChange
    rank: MetaOapg.properties.rank
    playerId: MetaOapg.properties.playerId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rank"]) -> MetaOapg.properties.rank: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["score"]) -> MetaOapg.properties.score: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["playerId"]) -> MetaOapg.properties.playerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stageChange"]) -> MetaOapg.properties.stageChange: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currencyRewards"]) -> MetaOapg.properties.currencyRewards: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["rank", "score", "playerId", "stageChange", "currencyRewards", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rank"]) -> MetaOapg.properties.rank: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["score"]) -> MetaOapg.properties.score: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["playerId"]) -> MetaOapg.properties.playerId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stageChange"]) -> MetaOapg.properties.stageChange: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currencyRewards"]) -> typing.Union[MetaOapg.properties.currencyRewards, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["rank", "score", "playerId", "stageChange", "currencyRewards", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        score: typing.Union[MetaOapg.properties.score, decimal.Decimal, int, float, ],
        stageChange: typing.Union[MetaOapg.properties.stageChange, decimal.Decimal, int, ],
        rank: typing.Union[MetaOapg.properties.rank, decimal.Decimal, int, ],
        playerId: typing.Union[MetaOapg.properties.playerId, decimal.Decimal, int, ],
        currencyRewards: typing.Union[MetaOapg.properties.currencyRewards, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TournamentEntry':
        return super().__new__(
            cls,
            *args,
            score=score,
            stageChange=stageChange,
            rank=rank,
            playerId=playerId,
            currencyRewards=currencyRewards,
            _configuration=_configuration,
            **kwargs,
        )

from beamable_python_sdk.model.tournament_reward import TournamentReward
