# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.object_announcements_object_id_claim.post import ClaimObjectAnnouncement
from beamable_python_sdk.paths.basic_announcements.post import CreateNewAnnouncement
from beamable_python_sdk.paths.basic_announcements.delete import DeleteAnnouncement
from beamable_python_sdk.paths.basic_announcements_list.get import GetAllAnnouncements
from beamable_python_sdk.paths.object_announcements_object_id.get import GetObjectDetails
from beamable_python_sdk.paths.object_announcements_object_id_raw.get import GetObjectRaw
from beamable_python_sdk.paths.object_announcements_object_id_read.put import MarkAsRead
from beamable_python_sdk.paths.object_announcements_object_id.delete import RemoveAnnouncementObject
from beamable_python_sdk.paths.basic_announcements_search.get import SearchOperation
from beamable_python_sdk.apis.tags.announcement_api_raw import AnnouncementApiRaw


class AnnouncementApi(
    ClaimObjectAnnouncement,
    CreateNewAnnouncement,
    DeleteAnnouncement,
    GetAllAnnouncements,
    GetObjectDetails,
    GetObjectRaw,
    MarkAsRead,
    RemoveAnnouncementObject,
    SearchOperation,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AnnouncementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AnnouncementApiRaw(api_client)
