# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_cloudsaving_data_commit_manifest.put import CommitManifestPutRaw
from beamable_python_sdk.paths.basic_cloudsaving_data.delete import DeleteDataRaw
from beamable_python_sdk.paths.basic_cloudsaving.get import GetDataRaw
from beamable_python_sdk.paths.basic_cloudsaving_data_download_url.post import GetDataDownloadUrlRaw
from beamable_python_sdk.paths.basic_cloudsaving_data_metadata.get import GetDataMetadataRaw
from beamable_python_sdk.paths.basic_cloudsaving_data_move.put import MoveDataPutRaw
from beamable_python_sdk.paths.basic_cloudsaving_data_replace.post import ReplaceDataRaw
from beamable_python_sdk.paths.basic_cloudsaving_data_upload_url.post import UploadDataUrlRaw
from beamable_python_sdk.paths.basic_cloudsaving_data_upload_url_from_portal.post import UploadUrlFromPortalRaw


class CloudsavingApiRaw(
    CommitManifestPutRaw,
    DeleteDataRaw,
    GetDataRaw,
    GetDataDownloadUrlRaw,
    GetDataMetadataRaw,
    MoveDataPutRaw,
    ReplaceDataRaw,
    UploadDataUrlRaw,
    UploadUrlFromPortalRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
