# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_legacy_entitlement_defs_grant.post import CreateLegacyEntitlementDefs
from beamable_python_sdk.paths.basic_legacy_entitlement_defs.put import CreateLegacyEntitlementDefs0
from beamable_python_sdk.paths.basic_legacy_entitlement_defs_claim.put import DefineEntitlementLegacy
from beamable_python_sdk.paths.basic_legacy_entitlement_defs_player.get import GetPlayerEntitlements
from beamable_python_sdk.paths.basic_legacy_entitlement_defs_revoke.delete import RevokeLegacyEntitlementDefs
from beamable_python_sdk.paths.basic_legacy_entitlement_defs_upload.post import UploadLegacyEntitlementDefs
from beamable_python_sdk.apis.tags.entitlement_api_raw import EntitlementApiRaw


class EntitlementApi(
    CreateLegacyEntitlementDefs,
    CreateLegacyEntitlementDefs0,
    DefineEntitlementLegacy,
    GetPlayerEntitlements,
    RevokeLegacyEntitlementDefs,
    UploadLegacyEntitlementDefs,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EntitlementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EntitlementApiRaw(api_client)
