# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.object_event_players_object_id_claim.post import ClaimObjectEventPlayersRaw
from beamable_python_sdk.paths.basic_events_calendar.get import GetCalendarEventsRaw
from beamable_python_sdk.paths.object_events_object_id.get import GetObjectEventsRaw
from beamable_python_sdk.paths.object_event_players_object_id.get import GetPlayersDataRaw
from beamable_python_sdk.paths.object_events_object_id_ping.get import PingObjectEventsRaw
from beamable_python_sdk.paths.object_events_object_id_refresh.put import RefreshObjectEventsRaw
from beamable_python_sdk.paths.object_events_object_id_end_phase.put import UpdateObjectEndPhaseRaw
from beamable_python_sdk.paths.object_event_players_object_id_score.put import UpdatePlayerScoreRaw


class EventApiRaw(
    ClaimObjectEventPlayersRaw,
    GetCalendarEventsRaw,
    GetObjectEventsRaw,
    GetPlayersDataRaw,
    PingObjectEventsRaw,
    RefreshObjectEventsRaw,
    UpdateObjectEndPhaseRaw,
    UpdatePlayerScoreRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
