# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_realms_game.post import CreateRealm
from beamable_python_sdk.paths.basic_realms_game.get import GetRealms
from beamable_python_sdk.paths.basic_realms_games.get import GetRealmsGames
from beamable_python_sdk.paths.basic_notification_game.post import PostNotification
from beamable_python_sdk.paths.object_gamerelay_object_id.post import RelayObjectPost
from beamable_python_sdk.paths.object_gamerelay_object_id_results.post import RelayObjectResults
from beamable_python_sdk.paths.object_gamerelay_object_id_sync.post import RelayObjectSync
from beamable_python_sdk.paths.basic_realms_game.put import UpdateRealm
from beamable_python_sdk.apis.tags.game_api_raw import GameApiRaw


class GameApi(
    CreateRealm,
    GetRealms,
    GetRealmsGames,
    PostNotification,
    RelayObjectPost,
    RelayObjectResults,
    RelayObjectSync,
    UpdateRealm,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GameApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GameApiRaw(api_client)
