# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_realms_launch_message.post import CreateLaunchMessage
from beamable_python_sdk.paths.basic_realms_launch_message.delete import DeleteLaunchMessage
from beamable_python_sdk.paths.basic_realms_launch_message.get import GetLaunchData
from beamable_python_sdk.paths.basic_social_my.get import GetMySocialData
from beamable_python_sdk.paths.object_chat_v2_object_id_messages.post import SendMessage
from beamable_python_sdk.paths.basic_push_send.post import SendPushNotification
from beamable_python_sdk.apis.tags.message_api_raw import MessageApiRaw


class MessageApi(
    CreateLaunchMessage,
    DeleteLaunchMessage,
    GetLaunchData,
    GetMySocialData,
    SendMessage,
    SendPushNotification,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MessageApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MessageApiRaw(api_client)
