# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_notification_custom.post import CreateCustomNotificationRaw
from beamable_python_sdk.paths.basic_notification.get import GetUnreadMessagesRaw
from beamable_python_sdk.paths.basic_notification_global.post import SendGlobalNotificationRaw
from beamable_python_sdk.paths.basic_notification_generic.post import SendNotificationRaw
from beamable_python_sdk.paths.basic_notification_player.post import SendPlayerNotificationRaw
from beamable_python_sdk.paths.basic_notification_server.post import SendServerNotificationRaw


class NotificationApiRaw(
    CreateCustomNotificationRaw,
    GetUnreadMessagesRaw,
    SendGlobalNotificationRaw,
    SendNotificationRaw,
    SendPlayerNotificationRaw,
    SendServerNotificationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
