# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_legacy_promos_claim.post import ClaimLegacyPromoRaw
from beamable_python_sdk.paths.basic_legacy_promos.post import CreateLegacyPromoRaw
from beamable_python_sdk.paths.basic_legacy_promos_codes.post import GeneratePromoCodeRaw
from beamable_python_sdk.paths.basic_legacy_promos.get import GetLegacyPromosRaw
from beamable_python_sdk.paths.basic_legacy_promos_codes.get import GetPromoCodesRaw


class PromoApiRaw(
    ClaimLegacyPromoRaw,
    CreateLegacyPromoRaw,
    GeneratePromoCodeRaw,
    GetLegacyPromosRaw,
    GetPromoCodesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
