# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_realms_customer_alias_available.get import CheckAliasAvailableRaw
from beamable_python_sdk.paths.basic_realms_is_customer.get import CheckCustomerStatusRaw
from beamable_python_sdk.paths.basic_realms_project_beamable.post import CreateBeamableRaw
from beamable_python_sdk.paths.basic_realms_customer.post import CreateCustomerRealmRaw
from beamable_python_sdk.paths.basic_realms_project.post import CreateProjectRealRaw
from beamable_python_sdk.paths.basic_realms_promotion.post import CreatePromotionRaw
from beamable_python_sdk.paths.basic_realms_project.delete import DeleteProjectRaw
from beamable_python_sdk.paths.basic_realms_config.get import GetConfigRaw
from beamable_python_sdk.paths.basic_realms_customer.get import GetCustomerRealmsRaw
from beamable_python_sdk.paths.basic_realms_admin_customer.get import GetCustomerRealms0Raw
from beamable_python_sdk.paths.basic_realms_project.get import GetProjectRealmsRaw
from beamable_python_sdk.paths.basic_realms_promotion.get import GetPromotionDataRaw
from beamable_python_sdk.paths.basic_realms_customers.get import ListCustomersRealmsRaw
from beamable_python_sdk.paths.basic_realms_project_promote.post import ProjectPromoteRaw
from beamable_python_sdk.paths.basic_realms_project_promote.get import ProjectPromoteGetRaw
from beamable_python_sdk.paths.basic_realms_project_rename.put import RenameProjectRealmsRaw
from beamable_python_sdk.paths.basic_realms_config.put import UpdateConfigRaw
from beamable_python_sdk.paths.basic_realms_project.put import UpdateProjectRealmsRaw


class RealmApiRaw(
    CheckAliasAvailableRaw,
    CheckCustomerStatusRaw,
    CreateBeamableRaw,
    CreateCustomerRealmRaw,
    CreateProjectRealRaw,
    CreatePromotionRaw,
    DeleteProjectRaw,
    GetConfigRaw,
    GetCustomerRealmsRaw,
    GetCustomerRealms0Raw,
    GetProjectRealmsRaw,
    GetPromotionDataRaw,
    ListCustomersRealmsRaw,
    ProjectPromoteRaw,
    ProjectPromoteGetRaw,
    RenameProjectRealmsRaw,
    UpdateConfigRaw,
    UpdateProjectRealmsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
