# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_push_register.post import PushUser
from beamable_python_sdk.apis.tags.registration_api_raw import RegistrationApiRaw


class RegistrationApi(
    PushUser,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RegistrationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RegistrationApiRaw(api_client)
