# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_legacy_shards.delete import DeleteLegacyShard
from beamable_python_sdk.paths.basic_legacy_shards_accepting.get import GetLegacyAccepting
from beamable_python_sdk.paths.basic_legacy_shards.get import GetLegacyData
from beamable_python_sdk.paths.basic_legacy_shards_preferred.get import GetPreferredLegacyShards
from beamable_python_sdk.paths.basic_legacy_shards.post import PostLegacyShard
from beamable_python_sdk.paths.basic_legacy_shards.put import UpdateLegacyShardData
from beamable_python_sdk.apis.tags.shard_api_raw import ShardApiRaw


class ShardApi(
    DeleteLegacyShard,
    GetLegacyAccepting,
    GetLegacyData,
    GetPreferredLegacyShards,
    PostLegacyShard,
    UpdateLegacyShardData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ShardApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ShardApiRaw(api_client)
