# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_commerce_skus.post import CreateSku
from beamable_python_sdk.paths.basic_commerce_skus.get import ListSkus
from beamable_python_sdk.apis.tags.sku_api_raw import SKUApiRaw


class SKUApi(
    CreateSku,
    ListSkus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SKUApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SKUApiRaw(api_client)
