# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_tournaments_admin_player.get import AdminPlayerDataGet
from beamable_python_sdk.paths.basic_tournaments.post import CreateNewTournament
from beamable_python_sdk.paths.basic_tournaments_rewards.post import CreateReward
from beamable_python_sdk.paths.basic_tournaments_champions.get import GetChampions
from beamable_python_sdk.paths.basic_tournaments_global.get import GetGlobalTournaments
from beamable_python_sdk.paths.basic_tournaments_me.get import GetMyTournament
from beamable_python_sdk.paths.basic_tournaments_rewards.get import GetRewards
from beamable_python_sdk.paths.basic_tournaments_standings.get import GetStandings
from beamable_python_sdk.paths.object_tournaments_object_id.get import GetTournamentObject
from beamable_python_sdk.paths.basic_tournaments.get import ListTournaments
from beamable_python_sdk.paths.basic_tournaments_score.post import SubmitScore
from beamable_python_sdk.paths.basic_tournaments_admin_player.put import UpdateAdminPlayer
from beamable_python_sdk.apis.tags.tournament_api_raw import TournamentApiRaw


class TournamentApi(
    AdminPlayerDataGet,
    CreateNewTournament,
    CreateReward,
    GetChampions,
    GetGlobalTournaments,
    GetMyTournament,
    GetRewards,
    GetStandings,
    GetTournamentObject,
    ListTournaments,
    SubmitScore,
    UpdateAdminPlayer,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TournamentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TournamentApiRaw(api_client)
