# coding: utf-8

"""
    history basic

    var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.

    The version of the OpenAPI document: 1.0
    Contact: support@beamable.com
    Created by: https://api.beamable.com
"""

from beamable_python_sdk.paths.basic_trials_admin_data.get import AdminDataGet
from beamable_python_sdk.paths.basic_trials.post import CreateNewTrial
from beamable_python_sdk.paths.basic_trials_data.delete import DeleteData
from beamable_python_sdk.paths.basic_trials_admin.get import GetAdminTrials
from beamable_python_sdk.paths.basic_trials.get import ListTrials
from beamable_python_sdk.paths.basic_trials_pause.put import PauseTrial
from beamable_python_sdk.paths.basic_trials_data.post import PostData
from beamable_python_sdk.paths.basic_trials.delete import RemoveTrial
from beamable_python_sdk.paths.basic_trials_schedule.put import SchedulePut
from beamable_python_sdk.paths.basic_trials_start.put import StartTrialProcess
from beamable_python_sdk.apis.tags.trial_api_raw import TrialApiRaw


class TrialApi(
    AdminDataGet,
    CreateNewTrial,
    DeleteData,
    GetAdminTrials,
    ListTrials,
    PauseTrial,
    PostData,
    RemoveTrial,
    SchedulePut,
    StartTrialProcess,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TrialApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TrialApiRaw(api_client)
